export const bioData = [
  "Content Strategy",
  "Content Creation",
  "Content Writing",
  "Content Creation",
  "Content Pillar",
  "Content Strategy",
  "Content Creation",
  "Content Creation",
  "Content Writing",
  "Content Strategy",
  "Content Creation",
  "Content Writing",
  "Content Creation",
  "Content Pillar",
  "Content Strategy",
  "Content Creation",
  "Content Creation",
  "Content Writing",
];
